WebBanHang/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Net;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class QuanLyDonHangController : Controller
    {
        private WebBanHangDbContext db = new WebBanHangDbContext();
        // GET: QuanLyDonHang
        public ActionResult DonHangChuaThanhToan()
        {
            var listctt = db.DonDatHangs.Where(n => n.DaThanhToan == false).OrderBy(n => n.NgatDat);
            return View(listctt);
        }
        public ActionResult DonHangChuaGiao()
        {
            var listcg = db.DonDatHangs.Where(n => n.TinhTrang == false).OrderBy(n => n.NgatDat);
            return View(listcg);
        }
        public ActionResult DonHangHoanThanh()
        {
            var listht = db.DonDatHangs.Where(n => n.TinhTrang == true && n.DaThanhToan == true).OrderBy(n => n.NgatDat);
            return View(listht);
        }
        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }
            var listChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDDH == id);
            ViewBag.listChiTietDH = listChiTietDH;
            return View(donDatHang);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DuyetDonHang([Bind(Include = "MaDDH,NgatDat,TinhTrang,NgayGiao,DaThanhToan,DaHuy,UuDai,MaKH")] DonDatHang donDatHang)
        {
            DonDatHang ddhupdate = db.DonDatHangs.Single(n => n.MaDDH == donDatHang.MaDDH);
            if (ModelState.IsValid)
            {
                ddhupdate.DaThanhToan = donDatHang.DaThanhToan;
                ddhupdate.TinhTrang = donDatHang.TinhTrang;
                db.SaveChanges();
                return RedirectToAction("DonHangHoanThanh");
            }                  
            var listChiTietDH = db.ChiTietDonDatHangs.Where(n => n.MaDDH == donDatHang.MaDDH);
            ViewBag.listChiTietDH = listChiTietDH;
            return View(donDatHang);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBanHang/Views/QuanLyDonHang/DonHangChuaGiao.cshtml
@model IEnumerable<WebBanHang.Models.DonDatHang>
@{
    ViewBag.Title = "DonHangChuaGiao";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<h1> Quản lý đơn hàng</h1>
<ul class="nav nav-tabs">
    <li role="presentation">
        <a class="active" href="@Url.Action("DonHangChuaGiao","QuanLyDonHang")">Đơn hàng chưa giao</a>
    </li>
    <li role="presentation">
        <a href="@Url.Action("DonHangChuaThanhToan","QuanLyDonHang")">Đơn hàng chưa thanh toán</a>
    </li>
    <li role="presentation">
        <a href="@Url.Action("DonHangHoanThanh","QuanLyDonHang")">Đơn Hàng  hoàn thành </a>
    </li>
</ul>
<table class="table">
    <tr>
        <th>
            Mã đơn hàng
        </th>
        <th>
            Tên Khách hàng
        </th>
        <th>
            Ngày Đặt
        </th>
        <th>
            Ngày giao
        </th>
        <th>
            Tình Trạng Giao Hàng
        </th>
        <th>
            Tình trạng thanh toán
        </th>
        <th>
            Ưu đãi
        </th>
        <th>
            Đã Hủy
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDDH)
            </td>
            <td>
                @if (item.MaKH != null)
                {
                    @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgatDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaThanhToan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaHuy)
            </td>

            <td>
                @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = item.MaDDH }) |

            </td>
        </tr>
    }

</table>

WebBanHang/Views/QuanLyDonHang/DonHangChuaThanhToan.cshtml
@model IEnumerable<WebBanHang.Models.DonDatHang>
@{
    ViewBag.Title = "DonHangChuaThanhToan";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<h1> Quản lý đơn hàng</h1>
<ul class="nav nav-tabs">
    <li role="presentation">
        <a href="@Url.Action("DonHangChuaGiao","QuanLyDonHang")">Đơn hàng chưa giao</a>
    </li>
    <li role="presentation">
        <a class="active" href="@Url.Action("DonHangChuaThanhToan","QuanLyDonHang")">Đơn hàng chưa thanh toán</a>
    </li>
    <li role="presentation">
        <a href="@Url.Action("DonHangHoanThanh","QuanLyDonHang")">Đơn Hàng  hoàn thanh  </a>
    </li>
</ul>
<table class="table">
    <tr>
        <th>
            Mã đơn hàng
        </th>
        <th>
            Tên Khách hàng
        </th>
        <th>
            Ngày Đặt
        </th>
        <th>
            Ngày giao
        </th>
        <th>
            Tình Trạng Giao Hàng
        </th>
        <th>
            Tình trạng thanh toán
        </th>
        <th>
            Ưu đãi
        </th>
        <th>
            Đã Hủy
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDDH)
            </td>
            <td>
                @if (item.MaKH != null)
                {
                    @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgatDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaThanhToan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaHuy)
            </td>

            <td>
                @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = item.MaDDH }) |

            </td>
        </tr>
    }

</table>

WebBanHang/Views/QuanLyDonHang/DonHangHoanThanh.cshtml
@model IEnumerable<WebBanHang.Models.DonDatHang>

@{
    ViewBag.Title = "DonHangHoanThanh";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<h1> Quản lý đơn hàng</h1>
<ul class="nav nav-tabs">
    <li role="presentation">
        <a href="@Url.Action("DonHangChuaGiao","QuanLyDonHang")">Đơn hàng chưa giao</a>
    </li>
    <li role="presentation">
        <a href="@Url.Action("DonHangChuaThanhToan","QuanLyDonHang")">Đơn hàng chưa thanh toán</a>
    </li>
    <li role="presentation">
        <a class="active" href="@Url.Action("DonHangHoanThanh","QuanLyDonHang")">Đơn Hàng hoàn thanh  </a>
    </li>
</ul>
<table class="table">
    <tr>
        <th>
            Mã đơn hàng
        </th>
        <th>
            Tên Khách hàng
        </th>
        <th>
            Ngày Đặt
        </th>
        <th>
            Ngày giao
        </th>
        <th>
            Tình Trạng Giao Hàng
        </th>
        <th>
            Tình trạng thanh toán
        </th>
        <th>
            Ưu đãi
        </th>
        <th>
            Đã Hủy
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDDH)
            </td>
            <td>
                @if (item.MaKH != null)
                {
                    @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgatDat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayGiao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaThanhToan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaHuy)
            </td>
            <td>
                @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = item.MaDDH }) |

            </td>
        </tr>
    }

</table>

WebBanHang/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using WebBanHang.Models
@model DonDatHang
@{
    ViewBag.Title = "DuyetDonHang";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<h2>Duyệt Đơn Hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @{ IEnumerable<ChiTietDonDatHang> listChiTietDH = (IEnumerable<ChiTietDonDatHang>)ViewBag.listChiTietDH; }
        <table class="table" id="table">
            <tr>
                <td colspan="4">
                    <table class="table">
                        @Html.HiddenFor(model => model.MaDDH)
                        <tr>
                            <th>
                                Mã đơn hàng
                            </th>
                            <th>
                                Mã Khách Hàng
                            </th>
                            <th>
                                Tên Khách Hàng
                            </th>
                            <th>
                                Ngày đặt
                            </th>
                            <th>
                                Tình trạng Giao Hàng
                            </th>
                            <th>
                                Tình trạng thanh toán
                            </th>


                            <th></th>
                        </tr>
                        <tr>
                            <td>
                                @Model.MaDDH
                            </td>
                            <td>
                                @Model.MaKH
                            </td>
                            <td>
                                @if (Model.MaKH != null)
                                {
                                    @Model.KhachHang.TenKH
                                }
                            </td>
                            <td>
                                @Model.NgatDat
                            </td>
                            <td>
                                @Html.EditorFor(model => model.TinhTrang)
                            </td>
                            <td>
                                @Html.EditorFor(model => model.DaThanhToan)
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

            <tr>
                <td>
                    Sản phẩm
                </td>
                <td>
                    Hình ảnh
                </td>
                <td>
                    Số lượng
                </td>
                <td>
                    Dơn giá
                </td>
            </tr>
            @foreach (var item in listChiTietDH)
            {
                <tr>
                    <td>
                        @item.SanPham.TenSP
                    </td>

                    <td>
                        <img src="~/Content/AnhSanPham/@item.SanPham.HinhAnh" style="height:50px;width:50px;" />
                    </td>

                    <td>
                        @item.SoLuong
                    </td>
                    <td>
                        @item.Gia
                    </td>
                </tr>
            }
            <tr>
                <td align="right" colspan="4">
                    Tổng số lượng :@Model.ChiTietDonDatHangs.Sum(n => n.SoLuong) sản phẩm
                </td>
            </tr>
            <tr>
                <td align="right" colspan="4">
                    Tổng tiền :@Model.ChiTietDonDatHangs.Sum(n => n.Gia).Value.ToString("#,##") VNĐ
                </td>
            </tr>

        </table>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="In đơn hàng" class="btn btn-default" id="btnIn" />
                <input type="submit" style="background-color:forestgreen;" value="Duyệt đơn hàng" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    $("#btnIn").click(function () {
        var content = "<table>"+ $("#table").html()+"</table>";
        indonhang(content);
    });
    function indonhang(content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>DIV Contents</title>');
        printWindow.document.write('</head><body>');
        printWindow.document.write(content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>